#!/usr/bin/env bash

sxhkd &

host_monitor_setup_script=~/.config/bspwm/host_monitor_setup.sh
if [ -x "$(command -v ${host_monitor_setup_script})" ]; then
    ${host_monitor_setup_script}
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

bspc config border_width         2
bspc config window_gap          4
bspc config top_padding 3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#1e66f5"
bspc config normal_border_color "#7c7f93"

bspc rule -a zoom state=floating focus=off

# compositor
if [ -x "$(command -v picom)" ]; then
    picom &
elif [ -x "$(command -v compton)" ]; then
    compton &
fi

# polybar
polybar_launch_script=~/.config/polybar/launch.sh
if [ -x "$(command -v ${polybar_launch_script})" ]; then
    ${polybar_launch_script}
fi

# dunst
if [ -x "$(command -v dunst)" ]; then
    dunst &
fi

# keyboard config
if [ -x "$(command -v setxkbmap)" ]; then
    setxkbmap -layout us,ua -option grp:shift_caps_toggle
fi

# Wallpaper
# Source: https://www.reddit.com/r/wallpaper/comments/lqmuyg/one_more_time_by_me_3840x2160/
if [ -x "$(command -v feh)" ]; then
    feh --bg-fill ~/.config/bspwm/wallpaper.png
fi
