#!/usr/bin/env bash

sxhkd &

if [[ $(hostname) == 'al-thinkpad' ]] && xrandr | grep " connected " | grep -q HDMI-A-0; then
    bspc monitor eDP -d 1 2 3 4 5
    bspc monitor HDMI-A-0 -d 6 7 8 9 10
else
    bspc monitor -d 1 2 3 4 5 6 7 8 9 10
fi

if [[ $(hostname) == 'PC' ]]; then
    xrandr --output DP-2 --scale 0.75x0.75
fi

bspc config border_width         2
bspc config window_gap          4
bspc config top_padding 3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#fee801"
bspc config normal_border_color "#39c4b6"

bspc rule -a zoom state=floating focus=off

# compositor
if [ -x "$(command -v picom)" ]; then
    picom &
elif [ -x "$(command -v compton)" ]; then
    compton &
fi

# polybar
polybar_launch_script=~/.config/polybar/launch.sh
if [ -x "$(command -v ${polybar_launch_script})" ]; then
    ${polybar_launch_script}
fi

# dunst
if [ -x "$(command -v dunst)" ]; then
    dunst &
fi

# keyboard config
if [ -x "$(command -v setxkbmap)" ]; then
    setxkbmap -layout us,ru,ua -option grp:shift_caps_toggle
fi

# wallpaper
if [ -x "$(command -v feh)" ]; then
    feh --bg-center ~/.config/bspwm/wallpaper.jpg
fi
